version: '3.8'

services:
  vector:
    depends_on: 
      - elasticsearch
    image: timberio/vector:0.22.2-debian 
    hostname: vector
    deploy:
      replicas: 1
    ports: 
      - 8383:8383
    volumes: 
      - ./vector/vector.toml:/etc/vector/vector.toml:ro
      - log_share:/var/log/nginx:ro
  
  nginx:
    image: nginx:1.21.6
    hostname: nginx
    deploy:
      replicas: 1
    ports:
      - 8080:80
    volumes: 
      - log_share:/var/log/nginx:rw
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.3
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
       - 5601:5601

volumes:
  log_share: